#!/usr/bin/env bash
# stop-gate.sh — Deterministic check whether an engagement is allowed to
# stop. A weak LLM cannot self-rationalise its way past this script.
#
# Usage:
#   bash scripts/stop-gate.sh <target>          # exits 0 if stop is OK
#   bash scripts/stop-gate.sh <target> --why    # also prints the reasoning
#
# Exit codes:
#   0 — stop is permitted (a real success or fully-documented blocker)
#   1 — stop is NOT permitted (keep working — reason printed)
#   2 — usage error
#
# Stop is permitted iff at least one of:
#   A) reports/<target>/loot/user.txt   AND  reports/<target>/loot/root.txt
#      both exist and are non-empty (HTB-style flags).
#   B) reports/<target>/loot/<anything>flag<anything>.txt exists, non-empty,
#      and ENGAGEMENT.md "Flags / proof" section has at least one ticked box.
#   C) ENGAGEMENT.md "Stuck-gate / hypotheses" section contains 3 hypotheses
#      AND each has a non-pending result line, AND notes.md has the same
#      three hypothesis labels (H1/H2/H3) recorded.
#   D) AWAITING HUMAN — reports/<target>/HUMAN-HELP-REQUESTED.md exists,
#      its 'Status:' line says 'awaiting_human', AND ≥3 falsified bypass
#      attempts are recorded under 'Tried (falsified):'. This is a PAUSE,
#      not 'done'. Generated by scripts/request-human.sh per AGENTS.md R15.
#
# Anything else → keep working.

set -uo pipefail

WS="$(cd "$(dirname "$0")/.." && pwd)"
TARGET="${1:-}"
VERBOSE="${2:-}"

if [[ -z "$TARGET" ]]; then
  echo "Usage: bash scripts/stop-gate.sh <target> [--why]"
  exit 2
fi

SLUG="$(echo "$TARGET" | tr '/' '-' | tr -cd 'a-zA-Z0-9._-')"
DIR="$WS/reports/$SLUG"

if [[ ! -d "$DIR" ]]; then
  echo "❌ No engagement folder for '$TARGET'. Run: bash scripts/pentest.sh $TARGET"
  exit 1
fi

reason() {
  if [[ "$VERBOSE" == "--why" ]]; then
    echo "$1"
  fi
}

# A) HTB-style flags
USER_F="$DIR/loot/user.txt"
ROOT_F="$DIR/loot/root.txt"
if [[ -s "$USER_F" && -s "$ROOT_F" ]]; then
  reason "✅ STOP OK — user.txt and root.txt both present and non-empty."
  exit 0
fi

# B) Generic flag file + ticked proof box in ENGAGEMENT.md
ENG="$DIR/ENGAGEMENT.md"
if compgen -G "$DIR/loot/*flag*.txt" >/dev/null 2>&1; then
  if [[ -f "$ENG" ]] && grep -qE '^\s*-\s*\[x\].*(flag|proof|root\.txt|user\.txt|domain admin)' "$ENG" -i; then
    reason "✅ STOP OK — flag file in loot/ and ENGAGEMENT.md proof box ticked."
    exit 0
  fi
fi

# D) Awaiting human (Out-of-Band gate) — see AGENTS.md R15.
HHR="$DIR/HUMAN-HELP-REQUESTED.md"
if [[ -f "$HHR" ]]; then
  if grep -qE '^Status:\s*awaiting_human\b' "$HHR"; then
    TRIED_COUNT=$(awk '/^## Tried \(falsified\)/{flag=1;next} /^## /{flag=0} flag && /^[[:space:]]*[-*0-9]/' "$HHR" | grep -cE '^[[:space:]]*[-*0-9]')
    if (( TRIED_COUNT >= 3 )); then
      reason "⏸️  PAUSE OK — awaiting human (OOB gate). $TRIED_COUNT falsified bypasses recorded. Resume when Raquel responds."
      exit 0
    else
      reason "❌ HUMAN-HELP-REQUESTED.md exists but only $TRIED_COUNT falsified bypasses recorded; R15 requires ≥3."
    fi
  fi
fi

# C) Documented blocker — either path is acceptable:
#   C1) hypothesis bank shows ≥ 3 falsified entries AND any confirmed
#       hypothesis is chained, AND target-model.md was updated after the
#       3rd falsification (proves the operator pivoted before giving up).
#   C2) Legacy: ENGAGEMENT.md H1/H2/H3 lines + notes.md mirroring.

BANK="$DIR/hypotheses.json"
C1_OK="no"
if [[ -f "$BANK" ]]; then
  C1_VERDICT=$(python3 - "$BANK" "$DIR/target-model.md" <<'PY'
import json, sys, os
b_path, tm_path = sys.argv[1], sys.argv[2]
try:
    d = json.load(open(b_path))
except Exception:
    print("unreadable"); sys.exit(0)
items = d.get("items", [])
falsified = [i for i in items if i.get("result") == "falsified"]
confirmed = [i for i in items if i.get("result") == "confirmed"]
unchained = [i for i in confirmed if not i.get("chains_to")]
if len(falsified) < 3:
    print(f"need-falsified|got={len(falsified)}"); sys.exit(0)
if unchained:
    ids = ','.join(i['id'] for i in unchained[:5])
    print(f"unchained-confirmed|{ids}"); sys.exit(0)
last_fals = max(i.get("tested_at",0) for i in falsified)
tm_mtime = os.path.getmtime(tm_path) if os.path.exists(tm_path) else 0
if tm_mtime <= last_fals:
    print("model-not-updated"); sys.exit(0)
print("ok")
PY
  )
  if [[ "$C1_VERDICT" == "ok" ]]; then
    C1_OK="yes"
    reason "✅ STOP OK — hypothesis bank: ≥3 falsified, all confirmed are chained, target-model.md was updated after pivot."
    exit 0
  fi
fi

# C2 (legacy markdown path)
if [[ -f "$ENG" ]]; then
  H_LINES=$(grep -cE '^\s*-\s*\*\*H[123]\*\*' "$ENG" 2>/dev/null || echo 0)
  PENDING=$(grep -cE 'Result:\s*_pending_' "$ENG" 2>/dev/null || echo 0)
  if (( H_LINES >= 3 )) && (( PENDING == 0 )); then
    NOTES="$DIR/notes.md"
    if [[ -f "$NOTES" ]] && grep -q "H1" "$NOTES" && grep -q "H2" "$NOTES" && grep -q "H3" "$NOTES"; then
      reason "✅ STOP OK — ENGAGEMENT.md hypotheses + notes.md evidence (legacy path)."
      exit 0
    fi
  fi
fi

# If C1 was attempted but failed, surface the specific failure.
if [[ -n "${C1_VERDICT:-}" && "$C1_VERDICT" != "ok" ]]; then
  case "$C1_VERDICT" in
    need-falsified*)
      reason "❌ C1 path: need ≥3 falsified hypotheses in the bank ($C1_VERDICT)."
      ;;
    unchained-confirmed*)
      reason "❌ C1 path: confirmed hypotheses are unchained: ${C1_VERDICT#unchained-confirmed|}. Run hypotheses.sh chain <id> ..."
      ;;
    model-not-updated)
      reason "❌ C1 path: target-model.md has not been updated since the most recent falsification — you didn't pivot, you just gave up."
      ;;
  esac
fi

# Otherwise: not allowed to stop. Tell the model exactly what's missing.
cat <<EOF
❌ STOP NOT PERMITTED — engagement is not finished.

Target: $TARGET
Folder: $DIR

To stop, satisfy ONE of:

 A) Capture flags
    Create non-empty files:
      $DIR/loot/user.txt
      $DIR/loot/root.txt

 B) Generic proof + ticked engagement box
    - Drop a *flag*.txt into $DIR/loot/
    - Tick a "Flags / proof" checkbox in $DIR/ENGAGEMENT.md
      (e.g. "- [x] root.txt — <hash>")

 C) Documented blocker — EITHER:
    C1) Hypothesis bank shows ≥3 falsified entries; any confirmed
        hypothesis is chained; target-model.md was updated AFTER the
        most recent falsification (= you pivoted, not just gave up).
          bash scripts/hypotheses.sh stats
          bash scripts/hypotheses.sh chain <id> "<next-stage H>"
    C2) Legacy: H1/H2/H3 in ENGAGEMENT.md + mirrored in notes.md.

 D) Out-of-Band human gate (CAPTCHA / email-verify / MFA / KYC / OAuth)
    After ≥3 *falsified* technical bypasses, run:
      bash scripts/request-human.sh --target $TARGET --gate <kind> \
        --tried "<list>" --need "<one line>" --resume-with "<one line>"
    See AGENTS.md R15 for the bypass checklist. Bailing without 3
    falsified bypasses is a quitter's shortcut and will be rejected.

Until then: bash scripts/think.sh
EOF
exit 1
